/*
 * Copyright 2026 The Buildish Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import org.gradle.api.Action
import org.gradle.api.GradleException
import org.gradle.api.IsolatedAction
import org.gradle.api.Project
import org.gradle.api.Task
import org.gradle.api.tasks.wrapper.Wrapper
import org.gradle.util.GradleVersion
import java.io.ByteArrayInputStream
import java.io.File
import java.io.Serializable
import java.nio.ByteBuffer
import java.nio.charset.Charset
import java.nio.charset.CodingErrorAction
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.LinkOption
import java.nio.file.StandardOpenOption
import java.nio.file.attribute.PosixFilePermission
import java.security.MessageDigest
import java.util.Properties

/**
 * Enhances only the native `:wrapper` task of the top-level build.
 *
 * Configuration captures the root output directory and the launcher set that
 * existed before Gradle generates its normal Wrapper outputs. Capturing only
 * strings and booleans keeps the execution action serializable and avoids
 * consulting `Task.project` while the task executes. Gradle tracks the launcher
 * existence checks as configuration-cache inputs.
 *
 * After Gradle generates both launchers, the JAR, and the properties file, the
 * final action validates and prepares every retained output before changing any
 * Buildish-owned content. Publication is deliberately sequential rather than a
 * multi-file transaction: a write failure fails the task, and the repository
 * invariant plus version-control review form the recovery boundary.
 *
 * A project that already maintains one launcher keeps only that launcher. A
 * project with neither launcher keeps Gradle's normal pair during adoption.
 */
class BuildishAfterProjectAction : IsolatedAction<Project>, Serializable {
    override fun execute(project: Project) {
        if (project.gradle.parent == null && project.path == ":") {
            val rootProjectDirectory = project.projectDir.absolutePath
            val posixLauncherPresent = Files.exists(
                File(rootProjectDirectory, "gradlew").toPath(),
                LinkOption.NOFOLLOW_LINKS,
            )
            val windowsLauncherPresent = Files.exists(
                File(rootProjectDirectory, "gradlew.bat").toPath(),
                LinkOption.NOFOLLOW_LINKS,
            )
            // Gradle's Wrapper task always generates both launchers. Preserve a
            // project's existing launcher set, except that initial adoption
            // keeps the newly generated pair so the project has entry points.
            val initialAdoption = !posixLauncherPresent && !windowsLauncherPresent
            project.tasks.named(
                "wrapper",
                Wrapper::class.java,
                BuildishConfigureWrapperAction(
                    rootProjectDirectory,
                    posixLauncherPresent || initialAdoption,
                    windowsLauncherPresent || initialAdoption,
                ),
            )
        }
    }
}

/** Attaches the serializable finalizer without realizing or replacing `:wrapper`. */
class BuildishConfigureWrapperAction(
    private val rootProjectDirectory: String,
    private val retainPosixLauncher: Boolean,
    private val retainWindowsLauncher: Boolean,
) : Action<Wrapper>, Serializable {
    override fun execute(task: Wrapper) {
        task.doLast(
            BuildishFinalizeWrapperAction(
                rootProjectDirectory,
                retainPosixLauncher,
                retainWindowsLauncher,
            ),
        )
    }
}

/** Validates, patches, and publishes the canonical outputs generated by Gradle. */
class BuildishFinalizeWrapperAction(
    private val rootProjectDirectory: String,
    private val retainPosixLauncher: Boolean,
    private val retainWindowsLauncher: Boolean,
) : Action<Task>, Serializable {
    override fun execute(task: Task) {
        val wrapper = task as Wrapper
        val posixFile = wrapper.scriptFile
        val windowsFile = wrapper.batchScript
        val jarFile = wrapper.jarFile
        val propertiesFile = wrapper.propertiesFile

        validateCanonicalOutputs(
            rootProjectDirectory,
            listOf(
                "POSIX launcher" to posixFile,
                "Windows launcher" to windowsFile,
                "Wrapper JAR" to jarFile,
                "Wrapper properties" to propertiesFile,
            ),
        )

        val executingVersion = GradleVersion.current().version
        validateStableVersion(executingVersion, "executing Gradle version")
        val wrapperDigest = sha256(jarFile)

        // Complete every read, structural check, and transformation before the
        // first Buildish-owned write. A preparation failure therefore publishes
        // no Buildish markers or metadata; Gradle or earlier task actions may
        // still have changed the generated outputs.
        val posix = if (retainPosixLauncher) {
            readText(posixFile, StandardCharsets.UTF_8, "POSIX launcher")
        } else {
            validateGeneratedLauncherForRemoval(posixFile, "POSIX launcher")
            null
        }
        val windows = if (retainWindowsLauncher) {
            readText(windowsFile, StandardCharsets.UTF_8, "Windows launcher")
        } else {
            validateGeneratedLauncherForRemoval(windowsFile, "Windows launcher")
            null
        }
        val properties = readText(
            propertiesFile,
            StandardCharsets.ISO_8859_1,
            "Wrapper properties",
        )
        val posixPermissions = if (retainPosixLauncher) readPosixPermissions(posixFile) else null
        val windowsPermissions = if (retainWindowsLauncher) readPosixPermissions(windowsFile) else null

        validateCleanLaunchers(posix, windows)
        val preparedPosix = posix?.let(::patchPosix)
        val preparedWindows = windows?.let(::patchWindows)
        val preparedProperties = patchProperties(
            properties,
            executingVersion,
            wrapperDigest,
        )

        if (preparedPosix != null) {
            writeExisting(posixFile, preparedPosix)
            verifyPosixPermissions(posixFile, posixPermissions)
        } else {
            Files.delete(posixFile.toPath())
        }
        if (preparedWindows != null) {
            writeExisting(windowsFile, preparedWindows)
            verifyPosixPermissions(windowsFile, windowsPermissions)
        } else {
            Files.delete(windowsFile.toPath())
        }
        writeExisting(propertiesFile, preparedProperties)
    }

    private fun validateGeneratedLauncherForRemoval(file: File, description: String) {
        if (!Files.isRegularFile(file.toPath(), LinkOption.NOFOLLOW_LINKS)) {
            fail("generated $description selected for removal is not a regular file: $file")
        }
    }

    private fun validateCanonicalOutputs(
        rootProjectDirectory: String,
        outputs: List<Pair<String, File>>,
    ) {
        val root = File(rootProjectDirectory).toPath().toAbsolutePath().normalize()
        val expected = listOf(
            root.resolve("gradlew"),
            root.resolve("gradlew.bat"),
            root.resolve("gradle/wrapper/gradle-wrapper.jar"),
            root.resolve("gradle/wrapper/gradle-wrapper.properties"),
        )
        for ((index, output) in outputs.withIndex()) {
            val actual = output.second.toPath().toAbsolutePath().normalize()
            if (actual != expected[index]) {
                fail(
                    "${output.first} must use the canonical project path " +
                        "${expected[index]}, found $actual",
                )
            }
        }
    }

    private fun validateCleanLaunchers(
        posix: BuildishTextContent?,
        windows: BuildishTextContent?,
    ) {
        val markers = listOf(
            "# BEGIN BUILDISH WRAPPER BOOTSTRAP",
            "# END BUILDISH WRAPPER BOOTSTRAP",
            "@rem BEGIN BUILDISH WRAPPER BOOTSTRAP",
            "@rem END BUILDISH WRAPPER BOOTSTRAP",
        )
        for ((description, content) in listOfNotNull(
            posix?.let { "POSIX launcher" to it },
            windows?.let { "Windows launcher" to it },
        )) {
            for (marker in markers) {
                val count = content.lines.count { it == marker }
                if (count != 0) {
                    fail("$description is not a clean generated launcher: found marker $marker")
                }
            }
        }
        if (windows?.lines?.any { it == ":buildishWrapperReady" } == true) {
            fail("Windows launcher is not a clean generated launcher: Buildish label already exists")
        }
    }

    // Internal visibility is intentional: the checked-in fixture appends a
    // narrow task to a temporary copy of this script and exercises these exact
    // production transformations without running Gradle's Wrapper generator.
    internal fun patchPosix(content: BuildishTextContent): BuildishTextContent {
        // Match one complete generated line, not a Gradle version. Template
        // drift fails closed until its structure and fixtures are reviewed.
        val anchor =
            "APP_HOME=${'$'}( cd -P \"${'$'}{APP_HOME:-./}\" > /dev/null && " +
                "printf '%s\\n' \"${'$'}PWD\" ) || exit"
        val index = uniqueLine(content, anchor, "POSIX APP_HOME insertion anchor")
        val replacement = listOf(
            anchor,
            "",
            "# BEGIN BUILDISH WRAPPER BOOTSTRAP",
            ". \"${'$'}APP_HOME/gradle/buildish-wrapper-bootstrap.sh\" || exit ${'$'}?",
            "# END BUILDISH WRAPPER BOOTSTRAP",
        )
        return content.withLines(
            content.lines.take(index) + replacement + content.lines.drop(index + 1),
        )
    }

    internal fun patchWindows(content: BuildishTextContent): BuildishTextContent {
        // The invocation matcher accepts template formatting changes only when
        // the ordered Java command contract remains unambiguous.
        val insertionAnchor = "for %%i in (\"%APP_HOME%\") do set APP_HOME=%%~fi"
        val insertionIndex = uniqueLine(
            content,
            insertionAnchor,
            "Windows APP_HOME insertion anchor",
        )
        val matches = content.lines.withIndex().filter { isWindowsJavaInvocation(it.value) }
        if (matches.size != 1) {
            fail("expected exactly one supported Windows Java invocation, found ${matches.size}")
        }
        val invocationIndex = matches.single().index
        val invocation = content.lines[invocationIndex]
        if (countOccurrences(invocation, "%*") != 1) {
            fail("Windows Java invocation must contain exactly one %* argument token")
        }
        val patchedInvocation = invocation.replace(
            "%*",
            "--init-script \"%APP_HOME%\\gradle\\buildish-wrapper.init.gradle.kts\" %*",
        )
        val insertion = listOf(
            insertionAnchor,
            "",
            "@rem BEGIN BUILDISH WRAPPER BOOTSTRAP",
            "if exist \"%APP_HOME%\\gradle\\wrapper\\gradle-wrapper.jar\" goto buildishWrapperReady",
            "powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass " +
                "-File \"%APP_HOME%\\gradle\\buildish-wrapper-bootstrap.ps1\"",
            "if errorlevel 1 exit /b %ERRORLEVEL%",
            ":buildishWrapperReady",
            "@rem END BUILDISH WRAPPER BOOTSTRAP",
        )
        val patchedLines = content.lines.toMutableList()
        patchedLines[invocationIndex] = patchedInvocation
        patchedLines.removeAt(insertionIndex)
        patchedLines.addAll(insertionIndex, insertion)
        return content.withLines(patchedLines)
    }

    private fun isWindowsJavaInvocation(line: String): Boolean {
        val tokens = listOf(
            "\"%JAVA_EXE%\"",
            "%DEFAULT_JVM_OPTS%",
            "%JAVA_OPTS%",
            "%GRADLE_OPTS%",
            "-jar \"%APP_HOME%\\gradle\\wrapper\\gradle-wrapper.jar\"",
            "%*",
        )
        var previous = -1
        for (token in tokens) {
            val index = line.indexOf(token, previous + 1)
            if (index < 0) {
                return false
            }
            previous = index
        }
        return true
    }

    internal fun patchProperties(
        content: BuildishTextContent,
        executingVersion: String,
        wrapperDigest: String,
    ): BuildishTextContent {
        // Java properties allow alternate separators, escaping, and continued
        // lines. Buildish-owned security values use one strict physical line so
        // both bootstrap implementations read exactly the state written here.
        for (line in content.lines) {
            if (hasContinuation(line)) {
                fail("Wrapper properties contains an unsupported continued property")
            }
        }

        val distributionUrlLines = propertyLines(content, "distributionUrl")
        if (distributionUrlLines.size != 1) {
            fail(
                "Wrapper properties must contain exactly one distributionUrl definition; " +
                    "found ${distributionUrlLines.size}",
            )
        }
        val distributionUrlLine = distributionUrlLines.single()
        if (!distributionUrlLine.startsWith("distributionUrl=")) {
            fail("distributionUrl must use the canonical distributionUrl=value form")
        }

        val distributionDigestLines = propertyLines(content, "distributionSha256Sum")
        if (distributionDigestLines.size != 1) {
            fail(
                "Wrapper properties must contain exactly one distributionSha256Sum definition; " +
                    "found ${distributionDigestLines.size}",
            )
        }
        if (!distributionDigestLines.single().matches(
                Regex("distributionSha256Sum=[0-9a-f]{64}"),
            )
        ) {
            fail("distributionSha256Sum must be one canonical lowercase SHA-256 line")
        }

        val loaded = Properties()
        try {
            loaded.load(ByteArrayInputStream(content.bytes()))
        } catch (error: IllegalArgumentException) {
            fail("Wrapper properties cannot be decoded: ${error.message}")
        }
        val distributionUrl = loaded.getProperty("distributionUrl")
            ?: fail("Wrapper properties has no logical distributionUrl")
        val targetVersionMatch = Regex(
            "https://services\\.gradle\\.org/distributions/" +
                "gradle-((?:0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)\\." +
                "(?:0|[1-9][0-9]*))-bin\\.zip",
        ).matchEntire(distributionUrl)
            ?: fail("distributionUrl is not a canonical stable Gradle binary distribution: $distributionUrl")
        validateStableVersion(targetVersionMatch.groupValues[1], "target Gradle version")

        // The executing Wrapper JAR identity is independent from the target
        // distribution version. A normal first upgrade pass may retain A here
        // while distributionUrl already selects B.
        val versionLines = propertyLines(content, "buildishWrapperJarVersion")
        if (versionLines.size > 1) {
            fail("Wrapper properties contains duplicate buildishWrapperJarVersion definitions")
        }
        if (versionLines.singleOrNull()?.matches(
                Regex(
                    "buildishWrapperJarVersion=" +
                        "(?:0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)\\." +
                        "(?:0|[1-9][0-9]*)",
                ),
            ) == false
        ) {
            fail("buildishWrapperJarVersion uses a noncanonical form")
        }
        val digestLines = propertyLines(content, "buildishWrapperJarSha256Sum")
        if (digestLines.size > 1) {
            fail("Wrapper properties contains duplicate buildishWrapperJarSha256Sum definitions")
        }
        if (digestLines.singleOrNull()?.matches(
                Regex("buildishWrapperJarSha256Sum=[0-9a-f]{64}"),
            ) == false
        ) {
            fail("buildishWrapperJarSha256Sum uses a noncanonical form")
        }

        val removedKeys = setOf(
            "buildishWrapperJarVersion",
            "buildishWrapperJarSha256Sum",
        )
        val retained = content.lines.filter { line ->
            decodedPropertyKeys(line).none { it in removedKeys }
        }
        return content.withLines(
            retained + listOf(
                "buildishWrapperJarVersion=$executingVersion",
                "buildishWrapperJarSha256Sum=$wrapperDigest",
            ),
        )
    }

    private fun propertyLines(content: BuildishTextContent, key: String): List<String> =
        content.lines.filter { key in decodedPropertyKeys(it) }

    private fun validateStableVersion(version: String, description: String) {
        if (!version.matches(
                Regex("(?:0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)\\.(?:0|[1-9][0-9]*)"),
            )
        ) {
            fail("$description is not a canonical three-component stable version: $version")
        }
    }

    private fun decodedPropertyKeys(line: String): Set<String> {
        val properties = Properties()
        try {
            properties.load(
                ByteArrayInputStream((line + "\n").toByteArray(StandardCharsets.ISO_8859_1)),
            )
        } catch (error: IllegalArgumentException) {
            fail("Wrapper properties contains an invalid property line: ${error.message}")
        }
        return properties.stringPropertyNames()
    }

    private fun hasContinuation(line: String): Boolean {
        var count = 0
        for (index in line.indices.reversed()) {
            if (line[index] != '\\') {
                break
            }
            count += 1
        }
        return count % 2 == 1
    }

    private fun uniqueLine(
        content: BuildishTextContent,
        line: String,
        description: String,
    ): Int {
        val indexes = content.lines.withIndex().filter { it.value == line }.map { it.index }
        if (indexes.size != 1) {
            fail("expected exactly one $description, found ${indexes.size}")
        }
        return indexes.single()
    }

    private fun countOccurrences(value: String, token: String): Int {
        var count = 0
        var offset = 0
        while (true) {
            val index = value.indexOf(token, offset)
            if (index < 0) {
                return count
            }
            count += 1
            offset = index + token.length
        }
    }

    internal fun readText(
        file: File,
        charset: Charset,
        description: String,
    ): BuildishTextContent {
        val path = file.toPath()
        if (!Files.isRegularFile(path, LinkOption.NOFOLLOW_LINKS)) {
            fail("$description is not a regular file: $file")
        }
        val bytes = Files.readAllBytes(path)
        val decoder = charset.newDecoder()
            .onMalformedInput(CodingErrorAction.REPORT)
            .onUnmappableCharacter(CodingErrorAction.REPORT)
        val text = try {
            decoder.decode(ByteBuffer.wrap(bytes)).toString()
        } catch (error: Exception) {
            fail("$description is not valid ${charset.name()}: ${error.message}")
        }
        val withoutCrlf = text.replace("\r\n", "")
        if ('\r' in withoutCrlf) {
            fail("$description contains a bare carriage return")
        }
        val hasCrlf = "\r\n" in text
        val hasLf = '\n' in withoutCrlf
        if (hasCrlf && hasLf) {
            fail("$description contains mixed LF and CRLF newlines")
        }
        val newline = when {
            hasCrlf -> "\r\n"
            hasLf -> "\n"
            else -> fail("$description contains no newline")
        }
        val finalNewline = text.endsWith(newline)
        val body = if (finalNewline) text.dropLast(newline.length) else text
        val lines = if (body.isEmpty()) emptyList() else body.split(newline)
        return BuildishTextContent(lines, newline, finalNewline, charset)
    }

    private fun readPosixPermissions(file: File): Set<PosixFilePermission>? = try {
        Files.getPosixFilePermissions(file.toPath(), LinkOption.NOFOLLOW_LINKS).toSet()
    } catch (_: UnsupportedOperationException) {
        null
    }

    private fun verifyPosixPermissions(
        file: File,
        expected: Set<PosixFilePermission>?,
    ) {
        if (expected == null) {
            return
        }
        val actual = Files.getPosixFilePermissions(
            file.toPath(),
            LinkOption.NOFOLLOW_LINKS,
        )
        if (actual != expected) {
            fail("launcher mode changed while writing: $file")
        }
    }

    private fun writeExisting(file: File, content: BuildishTextContent) {
        Files.write(
            file.toPath(),
            content.bytes(),
            StandardOpenOption.WRITE,
            StandardOpenOption.TRUNCATE_EXISTING,
        )
    }

    private fun sha256(file: File): String {
        val path = file.toPath()
        if (!Files.isRegularFile(path, LinkOption.NOFOLLOW_LINKS)) {
            fail("generated Wrapper JAR is not a regular file: $file")
        }
        val digest = MessageDigest.getInstance("SHA-256")
        Files.newInputStream(path).use { input ->
            val buffer = ByteArray(8192)
            while (true) {
                val count = input.read(buffer)
                if (count < 0) {
                    break
                }
                digest.update(buffer, 0, count)
            }
        }
        return digest.digest().joinToString("") { "%02x".format(it) }
    }

    private fun fail(message: String): Nothing =
        throw GradleException("Buildish Wrapper integration: $message")
}

class BuildishTextContent(
    val lines: List<String>,
    private val newline: String,
    private val finalNewline: Boolean,
    private val charset: Charset,
) {
    /** Returns replacement lines while preserving encoding and newline style. */
    fun withLines(replacement: List<String>): BuildishTextContent =
        BuildishTextContent(replacement, newline, finalNewline, charset)

    fun bytes(): ByteArray {
        val text = lines.joinToString(newline) + if (finalNewline) newline else ""
        return text.toByteArray(charset)
    }
}

gradle.lifecycle.afterProject(BuildishAfterProjectAction())
